/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf -t -T 
Files: scene.gltf [22.75KB] > C:\Users\Nikita\projects\3d-work-space\public\models\book_stack\scene-transformed.glb [984.52KB] (-4228%)
Author: Paubr (https://sketchfab.com/paubr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/book-stack-90944ea5739248f6b707d6c2b0955c3b
Title: Book Stack
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
    defaultMaterial_1: THREE.Mesh
  }
  materials: {
    cover: THREE.MeshStandardMaterial
    paper: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d-work-space/models//book_stack/scene-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.cover} />
      <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.paper} />
    </group>
  )
}

useGLTF.preload('/3d-work-space/models//book_stack/scene-transformed.glb')
