/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf -t -T 
Files: scene.gltf [10.83KB] > C:\Users\Nikita\projects\3d-work-space\public\models\laptop_2\scene-transformed.glb [394.02KB] (-3538%)
Author: hellfa (https://sketchfab.com/hellfa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-d55ef30e28b1455bad46e0beeb85bfc6
Title: Laptop
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['podstawa_Material_#28_0']: THREE.Mesh
    ['klapa_Material_#41_0']: THREE.Mesh
    ['Sphere002_Material_#42_0']: THREE.Mesh
  }
  materials: {
    Material_28: THREE.MeshStandardMaterial
    Material_41: THREE.MeshStandardMaterial
    Material_42: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

const screenOffMaterial = new THREE.MeshStandardMaterial({
  color: '#111111', // Очень темный серый/черный
  emissive: '#000000', // Убираем свечение
  roughness: 1.0, // Максимальная шероховатость
  metalness: 0.0 // Без металличности
})

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/public/models/laptop_2/scene-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} scale={0.03} dispose={null}>
      <mesh geometry={nodes['podstawa_Material_#28_0'].geometry} material={materials.Material_28} position={[-50.569, 1.532, 47.852]} rotation={[-Math.PI / 2, 0, 0]} scale={[4.269, 5.129, 1]} />
      {/* Экран с выключенным материалом */}
      <mesh
        geometry={nodes['klapa_Material_#41_0'].geometry}
        material={screenOffMaterial} // Используем темный материал
        position={[-50.569, 16.992, -36]}
        rotation={[-0.554, 0, 0]}
        scale={[4.269, 5.129, 1]}
      />
      <mesh geometry={nodes['klapa_Material_#41_0'].geometry} material={materials.Material_41} position={[-50.569, 16.992, -37.251]} rotation={[-0.554, 0, 0]} scale={[4.269, 5.129, 1]} />
      <mesh geometry={nodes['Sphere002_Material_#42_0'].geometry} material={materials.Material_42} position={[61.864, 0.045, 62.738]} rotation={[Math.PI / 2, 0, 0]} scale={[0.931, 0.931, 0.284]} />
    </group>
  )
}

useGLTF.preload('/public/models/laptop_2/scene-transformed.glb')
