/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf -t -T 
Files: scene.gltf [13.51KB] > C:\Users\Nikita\projects\3d-work-space\public\models\white_shelf\scene-transformed.glb [2KB] (85%)
Author: antontomilenko19 (https://sketchfab.com/antontomilenko4)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/white-shelf-785079b837c246deb7cf61efcfb40482
Title: White shelf
*/

import * as THREE from 'three'
import  { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
  }
  materials: {
    ['Scene_-_Root']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/white_shelf/scene-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} position={[0.448, 0.86, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.026, 0.026, 0.299]} />
    </group>
  )
}

useGLTF.preload('/models/white_shelf/scene-transformed.glb')
