/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf -t -T 
Files: scene.gltf [9.52KB] > C:\Users\Nikita\projects\3d-work-space\public\models\laptop\scene-transformed.glb [94.33KB] (-891%)
Author: Uğur Yakışık (https://sketchfab.com/UgurYksk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-c1988d0aa23544c683adfe53c3cec0c0
Title: laptop
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_7: THREE.Mesh
    Object_9: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/laptop/scene-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.002']} position={[-0.929, 0, -0.308]} />
      {/* <mesh geometry={nodes.Object_5.geometry} material={materials.Material} position={[-0.929, 0, -0.308]} /> */}
      {/* подсветка клавы */}
      {/* <mesh geometry={nodes.Object_7.geometry} material={materials['Material.001']} position={[0, 0.13, 0]} /> */}
      {/* экран */}
      {/* <mesh geometry={nodes.Object_9.geometry} material={materials['Material.005']} position={[0, 1.408, -1.343]} rotation={[Math.PI / 2, 0, 0]} /> */}
    </group>
  )
}

useGLTF.preload('/models/laptop/scene-transformed.glb')
